#
# Installs the package without optional deps and sees we import nicely.
#
# This is to make the installation more manageable with Pyodide.
#
name: Web browser and Pyodide test suite
on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]

jobs:
  client-side-test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies
        run: poetry install --no-interaction
      # Poetry / Python issue
      # https://github.com/python-poetry/poetry/issues/6328
      # https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources
      - name: Fix No module named pkg_resources
        run: poetry run pip install setuptools
      - name: Run test scripts
        run: poetry run pytest tests/test_optional_dependencies.py
