name: Automated test suite
on:
  push:
    branches: [ master ]
    tags: [v*]
  pull_request:
    branches: [ master ]

jobs:
  automated-test-suite:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Get poetry
      run: |
        pip install poetry
    # See pyproject.toml for details
    - name: Setup master tracked dependencies and submodules
      run: |
        git submodule update --init --recursive
    - name: Install dependencies
      run: |
        poetry install
    - name: Install Ganache
      run: |
        npm install -g ganache
    - name: Run test scripts
      run: |
        poetry run pytest --tb=native
      env:
        TRADING_STRATEGY_API_KEY: ${{ secrets.TRADING_STRATEGY_API_KEY }}
        BNB_CHAIN_JSON_RPC: ${{ secrets.BNB_CHAIN_JSON_RPC }}

  build-binder:
    runs-on: ubuntu-latest
    needs: test
    # Skip build on master push
    if: github.event_name != 'push' || github.ref != 'refs/heads/master'
    steps:
      - name: Trigger binder-env build
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'tradingstrategy-ai',
              repo: 'binder-env',
              workflow_id: 'binder.yml',
              ref: 'master'
            })
